apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "aspnetapp-deployment"
  namespace: "default"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "aspnetapp"
    spec:
      containers:
      - image: mcr.microsoft.com/dotnet/core/samples:aspnetapp
        imagePullPolicy: Always
        name: "aspnetapp"
        ports:
        - containerPort: 80
